(() => {
'use strict';
const canvas=document.getElementById('game');
const ctx=canvas.getContext('2d');
const $=s=>document.querySelector(s);
const ui={time:$('#time'),squad:$('#squad'),hp:$('#hp'),kills:$('#kills'),phase:$('#phase'),lane:$('#lane'),mission:$('#mission'),progress:$('#progress'),reinforce:$('#reinforce'),reinforceBar:$('#reinforceBar'),danger:$('#danger'),dangerBar:$('#dangerBar'),overlay:$('#overlay'),card:$('#card'),banner:$('#banner'),stage:$('#stage'),pause:$('#pause'),sound:$('#sound')};
const W=720,H=900,ROAD_TOP=110,BASE_Y=770,LANES=[108,234,360,486,612];
const laneNames=['最左路','左路','中路','右路','最右路'];
const GROWTH=[{at:12,add:1},{at:30,add:1},{at:48,add:1},{at:66,add:1}];
let state,raf,last=0,audioOn=true,ac=null;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const rnd=(a,b)=>a+Math.random()*(b-a);
function beep(freq=360,dur=.05,type='square',vol=.025){if(!audioOn)return;try{ac=ac||new (window.AudioContext||window.webkitAudioContext)();const o=ac.createOscillator(),g=ac.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(vol,ac.currentTime);g.gain.exponentialRampToValueAtTime(.0001,ac.currentTime+dur);o.connect(g).connect(ac.destination);o.start();o.stop(ac.currentTime+dur)}catch{}}
function fresh(){return {running:false,paused:false,time:0,duration:80,hp:5,kills:0,playerX:360,targetX:360,soldiers:1,growthIndex:0,enemies:[],bullets:[],particles:[],floaters:[],spawnT:.8,shotT:0,screenShake:0,eliteSpawned:false,warning:null,keys:{}}}
function start(){state=fresh();state.running=true;ui.overlay.classList.add('hidden');showBanner('1 人开局',900);last=performance.now();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop)}
function end(win){state.running=false;const result=win?'防线守住了':'防线失守';ui.card.innerHTML=`<h2>${result}</h2><p>${win?'人数逐步成长后，你撑过了完整 80 秒。':'敌人突破了防线。优先把火力切到最靠近底部的一路。'}</p><div class="rules"><div class="rule"><b>${state.kills}</b><small>本局击杀</small></div><div class="rule"><b>${state.soldiers} 人</b><small>最终兵力</small></div><div class="rule"><b>${state.hp} / 5</b><small>剩余耐久</small></div></div><button id="again" class="primary big">重新开始</button>`;ui.overlay.classList.remove('hidden');$('#again').onclick=start;beep(win?760:120,.4,'sawtooth',.06)}
function showBanner(text,ms=1000){ui.banner.textContent=text;ui.banner.classList.add('show');setTimeout(()=>ui.banner.classList.remove('show'),ms)}
function nearestLane(x){let best=0,d=1e9;LANES.forEach((v,i)=>{const q=Math.abs(v-x);if(q<d){d=q;best=i}});return best}
function spawnEnemy(){const t=state.time;let type='grunt',r=Math.random();if(t>12&&r<.23)type='runner';if(t>24&&r<.18)type='shield';if(t>42&&r<.12)type='heavy';const lane=Math.floor(Math.random()*5);const cfg={grunt:{hp:2.2,speed:26,r:17,color:'#ff6570',label:'兵'},runner:{hp:1.55,speed:35,r:15,color:'#ffb24e',label:'冲'},shield:{hp:5.2,speed:20,r:19,color:'#58a7ff',label:'盾'},heavy:{hp:10.5,speed:14,r:25,color:'#bb72ff',label:'重'}}[type];state.enemies.push({type,lane,x:LANES[lane]+rnd(-9,9),y:ROAD_TOP-25,hp:cfg.hp,maxHp:cfg.hp,speed:cfg.speed,r:cfg.r,color:cfg.color,label:cfg.label,hit:0,charge:false,elite:false})}
function spawnElite(){state.eliteSpawned=true;state.enemies.push({type:'elite',lane:2,x:LANES[2],y:ROAD_TOP-55,hp:40,maxHp:40,speed:10,r:39,color:'#ff4a80',label:'将',hit:0,elite:true,skill:3.2});showBanner('精英怪出现：注意地面预警',1400)}
function addGrowth(item){state.soldiers+=item.add;state.growthIndex++;for(let i=0;i<32;i++)particle(state.playerX+rnd(-55,55),BASE_Y+72,rnd(-75,75),rnd(-210,-65),'#7fffc2',rnd(2,5),rnd(.45,1));showBanner(`伙伴加入 +${item.add}｜现在 ${state.soldiers} 人`,1300);beep(880,.18,'sawtooth',.07)}
function offsets(n){return {1:[[0,0]],2:[[-20,0],[20,0]],3:[[0,0],[-34,28],[34,28]],4:[[-24,0],[24,0],[-48,30],[48,30]],5:[[0,0],[-34,25],[34,25],[-68,50],[68,50]]}[n]||[[0,0]]}
function shoot(){const arr=offsets(state.soldiers);const dmg=state.soldiers===1?1.35:state.soldiers===2?1.0:.82;for(const [ox] of arr){const x=state.playerX+ox;state.bullets.push({x,y:BASE_Y-45,v:700,dmg,life:.86});muzzle(x,BASE_Y-48)}beep(state.soldiers===1?260:330,.025,'square',.012)}
function muzzle(x,y){for(let i=0;i<3;i++)particle(x+rnd(-3,3),y,rnd(-20,20),rnd(-100,-30),'#ffe266',rnd(1,3),rnd(.08,.2))}
function particle(x,y,vx,vy,color,size,life){state.particles.push({x,y,vx,vy,color,size,life,max:life})}
function floater(x,y,text,color='#fff'){state.floaters.push({x,y,text,color,life:.75})}
function hitEnemy(e,dmg){e.hp-=dmg;e.hit=.08;e.y-=1.8;for(let i=0;i<3;i++)particle(e.x+rnd(-8,8),e.y+rnd(-8,8),rnd(-70,70),rnd(-80,30),e.color,rnd(1,3),rnd(.15,.35));if(e.hp<=0){state.kills++;floater(e.x,e.y,'+'+(e.elite?25:1),e.elite?'#ffd557':'#c8ffed');for(let i=0;i<(e.elite?35:12);i++)particle(e.x,e.y,rnd(-180,180),rnd(-190,120),e.color,rnd(2,6),rnd(.25,.85));state.screenShake=e.elite?10:3;beep(e.elite?130:520,e.elite?.2:.05,'triangle',e.elite?.07:.02);return true}return false}
function damageBase(amount=1){state.hp=Math.max(0,state.hp-amount);ui.stage.classList.remove('damage');void ui.stage.offsetWidth;ui.stage.classList.add('damage');state.screenShake=12;beep(90,.18,'sawtooth',.07);showBanner(`防线 -${amount}`,600);if(state.hp<=0)end(false)}
function triggerWarning(){state.warning={x:state.playerX,y:BASE_Y-5,r:78,t:1.75,max:1.75};beep(180,.12,'sine',.04)}
function explodeWarning(){const w=state.warning;if(!w)return;for(let i=0;i<35;i++)particle(w.x,w.y,rnd(-190,190),rnd(-240,40),'#ff5f67',rnd(2,6),rnd(.3,.8));if(Math.abs(state.playerX-w.x)<w.r-8)damageBase(1);state.warning=null;state.screenShake=14}
function update(dt){if(!state.running||state.paused)return;state.time+=dt;if(state.time>=state.duration){end(true);return}
 const speed=640;const keyDir=(state.keys.ArrowLeft||state.keys.a?-1:0)+(state.keys.ArrowRight||state.keys.d?1:0);if(keyDir)state.targetX+=keyDir*speed*dt;state.targetX=clamp(state.targetX,70,W-70);state.playerX+=(state.targetX-state.playerX)*Math.min(1,dt*14);
 const next=GROWTH[state.growthIndex];if(next&&state.time>=next.at)addGrowth(next);if(!state.eliteSpawned&&state.time>=54)spawnElite();
 state.spawnT-=dt;if(state.spawnT<=0){spawnEnemy();const pressure=clamp(state.time/state.duration,0,1);state.spawnT=rnd(.62,.95)*(1-pressure*.3)}
 state.shotT-=dt;if(state.shotT<=0){shoot();state.shotT=state.soldiers===1?.16:.2}
 for(const b of state.bullets){b.y-=b.v*dt;b.life-=dt}
 for(const e of state.enemies){let sp=e.speed;if(e.type==='runner'&&e.y>470){sp*=1.75;e.charge=true}e.y+=sp*dt;e.hit=Math.max(0,e.hit-dt);if(e.elite){e.skill-=dt;if(e.skill<=0&&!state.warning){triggerWarning();e.skill=rnd(6,8)}}}
 if(state.warning){state.warning.t-=dt;if(state.warning.t<=0)explodeWarning()}
 for(let bi=state.bullets.length-1;bi>=0;bi--){const b=state.bullets[bi];if(b.life<=0||b.y<70){state.bullets.splice(bi,1);continue}let hit=false;for(let ei=state.enemies.length-1;ei>=0;ei--){const e=state.enemies[ei];if(Math.abs(b.x-e.x)<e.r*.72&&Math.abs(b.y-e.y)<e.r){let dmg=b.dmg;if(e.type==='shield')dmg*=.55;if(hitEnemy(e,dmg))state.enemies.splice(ei,1);hit=true;break}}if(hit)state.bullets.splice(bi,1)}
 for(let i=state.enemies.length-1;i>=0;i--){if(state.enemies[i].y>=BASE_Y-20){const e=state.enemies[i];state.enemies.splice(i,1);damageBase(e.elite?2:1);if(!state.running)return}}
 for(const p of state.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=250*dt;p.life-=dt}state.particles=state.particles.filter(p=>p.life>0);for(const f of state.floaters){f.y-=35*dt;f.life-=dt}state.floaters=state.floaters.filter(f=>f.life>0);state.screenShake=Math.max(0,state.screenShake-dt*24);updateUI()}
function updateUI(){const remain=Math.max(0,state.duration-state.time);ui.time.textContent=remain.toFixed(1)+' 秒';ui.squad.textContent=state.soldiers+' 人';ui.hp.textContent=state.hp+' / 5';ui.kills.textContent=state.kills;ui.phase.textContent=state.time<12?'单人开局':state.time<30?'双人协防':state.time<48?'逐步扩编':state.time<66?'精英压阵':'最后冲击';const li=nearestLane(state.playerX);ui.lane.textContent=laneNames[li];ui.progress.style.width=(state.time/state.duration*100)+'%';const next=GROWTH[state.growthIndex];if(next){const prev=state.growthIndex?GROWTH[state.growthIndex-1].at:0;ui.reinforceBar.style.width=clamp((state.time-prev)/(next.at-prev)*100,0,100)+'%';ui.reinforce.textContent=`下次 +${next.add}：${Math.max(0,next.at-state.time).toFixed(1)} 秒后`}else{ui.reinforceBar.style.width='100%';ui.reinforce.textContent=`成长完成：当前 ${state.soldiers} 人`}let d=null;for(const e of state.enemies)if(!d||e.y>d.y)d=e;if(d){ui.danger.textContent=`${laneNames[d.lane]}｜${d.type==='runner'?'冲锋兵':d.type==='shield'?'盾兵':d.type==='heavy'?'重装兵':d.elite?'精英将军':'普通兵'} 距离防线 ${Math.max(0,Math.round(BASE_Y-d.y))}`;ui.dangerBar.style.width=clamp(d.y/BASE_Y*100,0,100)+'%'}else{ui.danger.textContent='敌军尚未进入道路';ui.dangerBar.style.width='0%'}}
function draw(){ctx.save();if(state.screenShake)ctx.translate(rnd(-state.screenShake,state.screenShake),rnd(-state.screenShake,state.screenShake));drawBackground();drawWarning();drawEnemies();drawBullets();drawSquad();drawParticles();ctx.restore()}
function drawBackground(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#10283b');g.addColorStop(.45,'#16322f');g.addColorStop(1,'#0b1718');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='#193b32';ctx.fillRect(0,ROAD_TOP,W,BASE_Y-ROAD_TOP);for(let i=0;i<5;i++){const x=LANES[i];ctx.fillStyle=i%2?'#263b34':'#2b4239';ctx.beginPath();ctx.moveTo(x-50,ROAD_TOP);ctx.lineTo(x+50,ROAD_TOP);ctx.lineTo(x+74,BASE_Y);ctx.lineTo(x-74,BASE_Y);ctx.closePath();ctx.fill();ctx.strokeStyle='#4e6959';ctx.lineWidth=2;ctx.stroke();ctx.setLineDash([18,22]);ctx.strokeStyle='#879e7f44';ctx.beginPath();ctx.moveTo(x,ROAD_TOP);ctx.lineTo(x,BASE_Y);ctx.stroke();ctx.setLineDash([])}ctx.fillStyle='#14202a';ctx.fillRect(0,BASE_Y,W,H-BASE_Y);ctx.fillStyle='#3c6573';ctx.fillRect(0,BASE_Y-7,W,7);ctx.fillStyle='#7fffd0';ctx.fillRect(0,BASE_Y-4,W,3);ctx.fillStyle='#09131b';ctx.fillRect(0,86,W,26);ctx.font='700 14px sans-serif';ctx.textAlign='center';ctx.fillStyle='#bfe5ef';ctx.fillText('敌军推进方向 ↓',W/2,104)}
function drawWarning(){if(!state.warning)return;const w=state.warning,p=1-w.t/w.max;ctx.save();ctx.globalAlpha=.32+.25*Math.sin(p*14);ctx.fillStyle='#ff334a';ctx.beginPath();ctx.ellipse(w.x,w.y,w.r,w.r*.42,0,0,Math.PI*2);ctx.fill();ctx.lineWidth=5;ctx.strokeStyle='#ff7d80';ctx.stroke();ctx.globalAlpha=1;ctx.font='900 17px sans-serif';ctx.fillStyle='#fff';ctx.textAlign='center';ctx.fillText('危险区域',w.x,w.y+6);ctx.restore()}
function drawEnemies(){for(const e of state.enemies){ctx.save();ctx.translate(e.x,e.y);if(e.hit)ctx.filter='brightness(2.5)';ctx.fillStyle='#0008';ctx.beginPath();ctx.ellipse(0,e.r*.8,e.r*.95,e.r*.35,0,0,Math.PI*2);ctx.fill();if(e.type==='shield'){ctx.fillStyle='#74c8ff';ctx.beginPath();if(ctx.roundRect)ctx.roundRect(-e.r*.92,-e.r*.45,e.r*1.84,e.r*1.2,7);else ctx.rect(-e.r*.92,-e.r*.45,e.r*1.84,e.r*1.2);ctx.fill()}ctx.fillStyle=e.color;ctx.beginPath();ctx.arc(0,-e.r*.55,e.r*.48,0,Math.PI*2);ctx.fill();ctx.fillRect(-e.r*.46,-e.r*.15,e.r*.92,e.r*1.1);ctx.strokeStyle=e.color;ctx.lineWidth=Math.max(5,e.r*.25);ctx.beginPath();ctx.moveTo(-e.r*.2,e.r*.8);ctx.lineTo(-e.r*.45,e.r*1.3);ctx.moveTo(e.r*.2,e.r*.8);ctx.lineTo(e.r*.45,e.r*1.3);ctx.stroke();if(e.charge){ctx.strokeStyle='#ffde69';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-e.r*1.4,0);ctx.lineTo(-e.r*.8,0);ctx.moveTo(e.r*.8,0);ctx.lineTo(e.r*1.4,0);ctx.stroke()}ctx.fillStyle='#081219';ctx.font=`900 ${e.elite?22:13}px sans-serif`;ctx.textAlign='center';ctx.fillText(e.label,0,e.elite?8:3);ctx.fillStyle='#071018';ctx.fillRect(-e.r,-e.r*1.45,e.r*2,5);ctx.fillStyle=e.elite?'#ffd85e':'#72ffae';ctx.fillRect(-e.r,-e.r*1.45,e.r*2*(e.hp/e.maxHp),5);ctx.restore()}}
function drawBullets(){ctx.save();ctx.strokeStyle='#ffe36f';ctx.lineWidth=4;ctx.shadowBlur=14;ctx.shadowColor='#ffe36f';for(const b of state.bullets){ctx.beginPath();ctx.moveTo(b.x,b.y+18);ctx.lineTo(b.x,b.y-7);ctx.stroke()}ctx.restore()}
function drawSquad(){const arr=offsets(state.soldiers);for(let i=arr.length-1;i>=0;i--){const [ox,oy]=arr[i],x=state.playerX+ox,y=BASE_Y+32+oy;ctx.save();ctx.translate(x,y);ctx.fillStyle='#0008';ctx.beginPath();ctx.ellipse(0,19,19,7,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=i===0?'#59e4ff':'#75ffb3';ctx.beginPath();ctx.arc(0,-9,9,0,Math.PI*2);ctx.fill();ctx.fillRect(-8,0,16,25);ctx.strokeStyle='#baf7ff';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(-4,24);ctx.lineTo(-9,39);ctx.moveTo(4,24);ctx.lineTo(9,39);ctx.stroke();ctx.fillStyle='#18242b';ctx.fillRect(6,2,22,6);ctx.fillStyle='#ffe26f';ctx.fillRect(25,3,8,4);ctx.restore()}ctx.strokeStyle='#58eaff55';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(state.playerX,BASE_Y-3);ctx.lineTo(state.playerX,ROAD_TOP);ctx.stroke()}
function drawParticles(){for(const p of state.particles){ctx.globalAlpha=clamp(p.life/p.max,0,1);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;for(const f of state.floaters){ctx.globalAlpha=clamp(f.life/.75,0,1);ctx.font='900 18px sans-serif';ctx.textAlign='center';ctx.fillStyle=f.color;ctx.fillText(f.text,f.x,f.y)}ctx.globalAlpha=1}
function loop(t){const dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);draw();raf=requestAnimationFrame(loop)}
function pointer(e){const r=canvas.getBoundingClientRect();const p=e.touches?e.touches[0]:e;state.targetX=clamp((p.clientX-r.left)/r.width*W,70,W-70)}
canvas.addEventListener('mousemove',pointer);canvas.addEventListener('touchstart',e=>{pointer(e);e.preventDefault()},{passive:false});canvas.addEventListener('touchmove',e=>{pointer(e);e.preventDefault()},{passive:false});window.addEventListener('keydown',e=>{state.keys[e.key]=true;if(['ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault()});window.addEventListener('keyup',e=>state.keys[e.key]=false);
$('#play').onclick=start;$('#restart').onclick=start;ui.pause.onclick=()=>{if(!state.running)return;state.paused=!state.paused;ui.pause.textContent=state.paused?'继续':'暂停';showBanner(state.paused?'已暂停':'继续战斗',500)};ui.sound.onclick=()=>{audioOn=!audioOn;ui.sound.textContent='声音：'+(audioOn?'开':'关')};
state=fresh();updateUI();draw();
})();